### ISSUE TITLE
Specify a license?

### ISSUE THREAD

**Issue by sahansk2** [arxenix/uiuc-shibboleth-auth#2]
Hi there! This is a pretty interesting project, and I'd like to try to use it for our club's Discord and further contribute to the project in ways I can. However, this is a little difficult because there is [no license](https://choosealicense.com/no-permission/) specified for the project.

Would you be able to specify an open-source license (e.g. MIT, GPLv2, BSD, etc.) to specify terms of use and contributions?

**Comment by arxenix** [comment]
Thanks for letting me know, forgot to add one. Done :)

BTW, I'm currently in the process of rewriting this to support multiple discord servers as there are a few other uni-associated discords that have expressed interest. If you're able to wait a bit, you can piggyback off of our hosting instead of having to go through the hassle of self-hosting and getting approval from university IT for your shibboleth service provider.
